### ISSUE TITLE
Přejmenovat github actions

### ISSUE THREAD

**Issue by met** [cesko-digital/movapp-data#105]
Máme teď 2x Build from Airtable a stále se mi to plete.

@pionl Prosím, přejmenuj tu actions, která má dělat tu synchronizace na mobilní repozitáře na něco jiného 🙏 

![image](https://user-images.githubusercontent.com/59498/236222071-22ec4829-1584-4152-b7ef-abc8049beab9.png)

**Comment by pionl** [comment]
https://github.com/cesko-digital/movapp-data/actions/workflows/notify_new_data.yml

Jinak klidně můžeme posílat slack notifikace jestli chceš.

**Comment by met** [comment]
Supr, takhle zatím ok, díky.
