### ISSUE TITLE
stories_transformer.rb - rewrite to nodejs (TypeScript)

### ISSUE THREAD

**Issue by pionl** [cesko-digital/movapp-data#128]
As our whole data repo is written in TypeScript (NodeJS) it would be ideal to implement stories_transformer.rb in TypeScript to make it easier to use the repo (NodeJS is easy to install on any platform) and the tools more consistent.

**Comment by kubito** [comment]
I would suggest not rewriting it to TS as is. I suggest rewriting the web to use a new structure and create new scripts for data generation.

**Comment by met** [comment]
Yes, web will use new data structure. We wait for some developer to have time for this. 

stories_transformer.rb is temporary fix.

**Comment by pionl** [comment]
ok
