### ISSUE TITLE
New Authorization to Airtable API

### ISSUE THREAD

**Issue by met** [cesko-digital/movapp-data#81]
**We need to upgrade our access to Airtable during next months. Here is the annoucement.**

> You’re receiving this update because you have used the Airtable API in the last two years.
In January, we [launched new API authentication methods](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=a321c629d2444c98b27091a7212de0c1&_e=pLL2zZ4Qol9odG-MmzJctkvni6ITkZkLZZgO3rJKp85l2A9pF830JH54bjIO6A3lUjc4gH3K7e63-t_JdFByhme-64LfyMXC07OuSCJ9kffKcHQyFlMH5ey-yj9dg-jEmnjwog3s9f_w6HVPjllD4YX9SMeCoGb_gd1vtrs8gdQw0nrpgbKP0sRDnBRLATJpNXPiHnqtZXyLzOFafYU_WidoGjWNxA0YbRtzbiAmv5v3xWTeiey-rAbDB8-9yX_4hUmCifv75AYyEBRbLo6cUlvYet-5UqneOgCoWq-kFQFJ7Sxgw-gLQTgRIYM42fwfI_qMjdwQKbO4fH7BDu_o6iXmB1vS6FK6tz-VnKFQvoXNOVL5gqzL_m3S2aKtktWuCHNYl9B5uD86rhvG9Hn6unjh6O3Sr913ShhHWDs73hkWmunr_UaCYBQCMOhW-TtTQ_LLupK2jc4KwSBaQmdcTEfFPHTjYH0bVWnsp-_5NtxzpKhJ2_pNpNIdjgQxdpeRtgA8L7UyRtbiTwbyEL6uFh-k5F6Sxtx9k-UeWAwRc_GkfvhLlwTZHhRynxb9af6XaPTT-w2IOSRWfQ8yK2_WULZh6mXm1OZFKMQupMgj-j95f3ogf7bm9riQj2t7JWk1dVewYSdJqc1-TzkVAJSxtWjFz8AmZoaJl7UchRYbfsYfcXO8vFO51gnSM5GKn0PTRHaOWK4grOhzYdgt_5SjKw%3D%3D), personal access tokens and OAuth integrations, which are replacing Airtable API keys.

> How does this impact you? API keys (and therefore, any integration that used them to connect with Airtable) will continue to work until February 1st 2024. However, to ensure continued access to the Airtable API, you will need to start using the new authentication methods before February 1st 2024.

> If you or a developer on your team has used an Airtable API key to build API integrations with Airtable, please migrate to using [personal access tokens](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=a321c629d2444c98b27091a7212de0c1&_e=pLL2zZ4Qol9odG-MmzJctgRUDT2Wiu_7OMD9CdlS79109PGmBM6ttp4zHNBlS0Zu5o5gI-abqBudyC8--m7lzGXHvfNIiYvCoMgHVtLyYavMSarD9CTM5ItoI7OoG4QlYyDzmCSuBB2T5gXWuUlk6OhGR2xCDEpfNWJ4cqcEhJRgmjcBnUEN0CE9l4DM3TT15x_FKmmrDaLsNq1jqjeHqadESh7dULp1-8oXI19SLJvPAUZUMXaJb-l2PTn8pb95R1NRItntuRjhrgXPROSt3GHr3OF3SbKvhPGpHHhvTmAAvDAlZefmCgg2o2Xoh8qHKqUayd4MEKVPEp9uouDRIB5Zl_TF2oY_PGqNKQKqw9AY6-HfYKBbetl_2tpHyblvMSBnp0D3GMSI-wc4uwcwrFYebwlssjbhoMCUmrZjxY1ogQjJgm0a5sDhQm4YiOpLF6Ck7fsLPc3Qjuq18di2fw%3D%3D) to authenticate your API requests before February 1st 2024. Your API key usage can be directly replaced with a personal access token provided as an Authorization: Bearer header.

> If your API Key use is with a third-party integration, we recommend using [OAuth for authentication](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=a321c629d2444c98b27091a7212de0c1&_e=pLL2zZ4Qol9odG-MmzJctk7FJ81Fz3rH1e5w_qs0RB3XHINyMlN4_6JgBym6wWdbUdYJsKOEvFr8Jci6nRPy-FT7aTh_zNi9TVNJU2NkqgvCB4znbjk290tiBahBXlx7zNbd1PeQSmKCxR7YV39JOAKUkzGePUi5lheR0h5lzfAmqP9QFq1IZpswh-55lPRwuoNV2EWVQjBZmQGjVB8qFcVs-XWVESwg-itBByaO9c4M1c3zS1p8LGCH4FTZanyLlfXlJN9QeynBMRJFn-CrfJMAlfRG5SR0wCtkNUauVZafu4rGnjtAmM5I52TOcmTMjUMwtqKRVOwzwDfgk-aFIBaUpFNdCmD8ackOscFPZaMab5Xbe-pOlIeX8gipfV_i_pZBTjWlQ0SW5J7TTv76Yq2y3NQV67iQHKKZFVQ7DYc1VrN3uGcyNhS9zoumHryx1caR4P6pev3tShHMcHo3VQ%3D%3D). If you are unsure how to set up OAuth for a specific partner or OAuth is not currently available for that partner, we recommend you contact their team for details on when it will be available. Please note that we are working with all integration partners to migrate to our OAuth capabilities, and many will be doing so in the next several months. 

> In summary, Personal Access Tokens and OAuth are now available (as of January 2023). Airtable API keys will be [deprecated](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=a321c629d2444c98b27091a7212de0c1&_e=pLL2zZ4Qol9odG-MmzJctk7FJ81Fz3rH1e5w_qs0RB1kJ2oKYSJQ0jX2SrDOOXgAyq3Lp8Bh15hOJlCFf_46BHzbpsTW6wLPp3zYo1COHYO68Ng2esr8xI2QaAW2CI6RiSUgiJqq0eXHjoHWAq6krBkJPKXBRYvF07_Ybxh6NIsh2RLIWJUegn6HF5gsvHBr_wkW-EHU-g5rURDeWbN6dBDc7zlvacgmJ2lKdDySC9DN8HZHsnmjNRqjds_QRUieDDuagzLXCLzkl_t2pNceTB-83cTUm8NeQbFS59HjnY8-s_F314g3PDF38gJqA5dh1ivi2pespi0PSalg8TxHkYeMhDuuzrls_eDkUc29BmyCfimRWOkVYWKzXxIugwEbqn4VmU0FTIUgpYWWXgZf0tgs5MvRNCXZpvMB-wS7zWVZFc_ou8WPJaLXzYEUgGFvHwMakvTNeUtfU5wQ06lHug%3D%3D) on the following timeline:

> August 1st, 2023: Users will no longer be able to create new API keys
February 1st, 2024 (next year): Existing API keys cannot be used to access the Airtable API
To learn more about this change, please visit our [support article](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=a321c629d2444c98b27091a7212de0c1&_e=pLL2zZ4Qol9odG-MmzJctk7FJ81Fz3rH1e5w_qs0RB1kJ2oKYSJQ0jX2SrDOOXgAyq3Lp8Bh15hOJlCFf_46BHzbpsTW6wLPp3zYo1COHYN7eTim4es6UMNvbk7yzSsaEg-rJYj-XSeHSbRHFYdL4cIHABi25ts4Zya173VWfzm_d9N5-saIaN0PRMdcRN1vOH7li6EOmw2PIJy9SeiqMOsjyZNf_VrC-ssCtf2aNW9arh65ZeyMOUAM5fY3RwPXLIO_IM7R3IF14VuiBYb3hiWHRz_aTIkgKQb6anzvE-COVAx6Nl9aM2QCIgZqCUM6WOft75ROeZhLAIadcdBqAO1oSe-bj7ERK7bmHVrBGeYR41_TzctfVJbXbyLf0FLN_tB4lSBcEO33aQc_S9Q_CwbOZa2pLh-CsoP1NJMjgXbXTue4I_908xpASumg1Q3akYxRYvkcd9KTWKXI74C_FJ86dHDx9ClxxV6nsQ4QcswfpK8g8OY5DMf8lUwWNo-KeeoekUQbbOwSPwiXbhSM4o1kqw_LHbUC_knuVkBfyVW5hDE-R4Z9Xwkr5SxH5jEV2iVJdKlk4KrQjG6TPPtiHfPlijjujry6Ommfemmq5L_IFVrjXh4Jwz3Zg5yzczu1).

> Thanks,
> The Airtable API Team

**Comment by pionl** [comment]
@met Do we have "Service" account for AirTable? We need to create token and just switch it with API that is stored in secrets

**Comment by met** [comment]
@pionl No idea what you are asking. @zoul might know, maybe?

**Comment by zoul** [comment]
We are using someone’s API key to access the database. That would be probably yours, Martin? Take a look at https://airtable.com/create/apikey, do you have an existing API key there? If yes, you should create a new one at https://airtable.com/create/tokens. The new API key should have a read-only access to the DB (or do you also need to write to the DB?) Once created, @pionl or you can update the `AIRTABLE_API_KEY` secret [in this repo](https://github.com/cesko-digital/movapp-data/settings/secrets/actions), you can delete your legacy key at https://airtable.com/create/apikey and see if anything breaks.

**Comment by pionl** [comment]
Yes its my API KEY :) it would be more suitable to store API KEY from service account than my account (if I delete my account, this would stop work), if there is nothing like service account and no plans to cover this at cesko-digital then I use my API key again.

**Comment by zoul** [comment]
Sorry, too many Martins :) Can we switch to using Martin Hassman’s [personal access token](https://airtable.com/create/tokens)? He’s the project coordinator, so it’s perfectly reasonable to use his token IMO.

**Comment by pionl** [comment]
I agree 👍

**Comment by met** [comment]
DONE. Token on Github is updated. 

Job finished successfully https://github.com/cesko-digital/movapp-data/actions/runs/4225221045/jobs/7337211674

@pionl Please, try to delete your own Airtable API KEY and run job again if all works well.

Hope that is all?

**Comment by zoul** [comment]
>  It says "Do not share it with third-party services". I've just shared it with GitHub.

They have a different OAuth-based flow for real third-party services, so they don’t want you to use the personal access tokens for that. In this case GitHub is a part of “your own” app, so it’s not considered a third-party service IMO.

**Comment by pionl** [comment]
@met API key has been deleted. Thanks for the update!
